version: "3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - "8091:80"
        links:
            -  fpm
        volumes:
            - ./:/var/www/laravel-docker
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            -   ./:/var/www/laravel-docker
        links:
            - postgresql
            - mysql
        depends_on:
            -   mysql
            - postgresql

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_HOST=%
    postgresql:
        image: postgres:15
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=laravel
